# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlitr < Formula
  desc "sqlitr is a trivial Go/CGo SQLite CLI"
  homepage "https://github.com/neilotoole/sqlitr"
  version "0.1.16"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/neilotoole/sqlitr/releases/download/v0.1.16/sqlitr_0.1.16_darwin_amd64.tar.gz"
    sha256 "8537aaa6546aa23785ece55de4b64a964354f3b4bd17f2227c4228127dee2579"
  elsif OS.linux?
  end

  def install
    bin.install "sqlitr"
  end

  test do
    system "#{bin}/sqlitr --version"
  end
end
